### ISSUE TITLE
Adjust `React` import

### ISSUE THREAD

**Issue by CWSites** [amit08255/render-when#3]
Instead of using a generic import of all the things with react...

```import * as React from 'react';```

Why not be more specific around what is needed?

```import { Children, ReactNode } from 'react';```

**Comment by amit08255** [comment]
Hi @CWSites 
Kindly check this article from Kent C dodds. I suppose you must have heard about him. He is well known for his great course on React. This answers the question well.

https://epicreact.dev/importing-react-through-the-ages/

Also you can check out this Twitter thread

https://twitter.com/dan_abramov/status/1308736035321511939?t=2VpryKM7tk2yrAKLuhpbiw&s=19
